export const ActionTypes = {
    REST_LOADING: "REST_LOADING",
    REST_ERROR: "REST_ERROR",
    REST_SUCCESS: "REST_SUCCESS",

    PRODUCT_LOADING: "PRODUCT_LOADING",
    PRODUCT_ERROR: "PRODUCT_ERROR",
    PRODUCT_SUCCESS: "PRODUCT_SUCCESS",

    CART_LOADING: "CART_LOADING",
    CART_ERROR: "CART_ERROR",
    CART_SUCCESS: "CART_SUCCESS",
    ADD_ITEM: "ADD_ITEM",
    DEL_ITEM: "DEL_ITEM",
    UPDATE_ITEM: "UPDATE_ITEM"
}